# Inspecting Customer and Cleaning


In [1051]:
import pandas as pd
customers = pd.read_csv("supplyguard_data/customers.csv")
customers

,customer_id,customer_name,customer_type,province,city,registration_date,monthly_shipping_budget
0,C000001,Sipho Adams,Business,Gauteng,Centurion,2024-10-13,3530.20
1,C000002,Amanda Maseko,Business,Gauteng,Johannesburg,2022-01-26,1555.50
2,C000003,Karabo Mkhize,Individual,Limpopo,Polokwane,2019-03-04,13767.67
3,C000004,Bongani Sithole,Individual,KwaZulu-Natal,Richards Bay,2021-06-30,10034.40
4,C000005,Bongani Dlamini,Business,Eastern Cape,East London,2026-03-28,7054.38
...,...,...,...,...,...,...,...
100195,C050453,Tshepo Mokoena,Enterprise,Gauteng,Centurion,2021-02-20,8794.30
100196,C090710,Phumzile Van Wyk,Individual,Limpopo,Polokwane,2025-02-01,19299.14
100197,C052885,Mandla Moyo,Individual,Western Cape,Worcester,2024-01-15,23989.65
100198,C030964,Mpho Pillay,Individual,Western Cape,Stellenbosch,2021-05-18,956.39


In [1052]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100200 entries, 0 to 100199
Data columns (total 7 columns):
 #   Column                   Non-Null Count   Dtype  
---  ------                   --------------   -----  
 0   customer_id              100200 non-null  object 
 1   customer_name            100200 non-null  object 
 2   customer_type            100200 non-null  object 
 3   province                 100200 non-null  object 
 4   city                     99169 non-null   object 
 5   registration_date        100200 non-null  object 
 6   monthly_shipping_budget  99209 non-null   float64
dtypes: float64(1), object(6)
memory usage: 5.4+ MB


In [1053]:
# Checking for duplicates
customers[customers.duplicated() == True]

,customer_id,customer_name,customer_type,province,city,registration_date,monthly_shipping_budget
100000,C075722,Lindelwa Naidoo,Enterprise,Limpopo,Thohoyandou,2026-03-26,4938.25
100001,C080185,Amanda Maseko,Individual,Mpumalanga,Mbombela,2023-02-01,10775.52
100002,C019865,Bongani Mokoena,Individual,Mpumalanga,Mbombela,2018-12-25,6567.96
100003,C076700,Mandla Pillay,Business,Western Cape,Cape Town,2019-03-02,136120.93
100004,C092992,Bongani Pillay,Individual,KwaZulu-Natal,Richards Bay,2024-01-01,4799.09
...,...,...,...,...,...,...,...
100195,C050453,Tshepo Mokoena,Enterprise,Gauteng,Centurion,2021-02-20,8794.30
100196,C090710,Phumzile Van Wyk,Individual,Limpopo,Polokwane,2025-02-01,19299.14
100197,C052885,Mandla Moyo,Individual,Western Cape,Worcester,2024-01-15,23989.65
100198,C030964,Mpho Pillay,Individual,Western Cape,Stellenbosch,2021-05-18,956.39


In [1054]:
#Removing duplicates
customers = customers.drop_duplicates()

In [1055]:
#Changing date from object to datetime
customers['registration_date'] = pd.to_datetime(customers['registration_date'])

C:\Users\E1023380\AppData\Local\Temp\ipykernel_30760\2841362927.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  customers['registration_date'] = pd.to_datetime(customers['registration_date'])


In [1056]:
#Changing the NaT to Nan
customers['monthly_shipping_budget'] = pd.to_numeric(
customers['monthly_shipping_budget'],
errors='coerce'
)


C:\Users\E1023380\AppData\Local\Temp\ipykernel_30760\1203537362.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  customers['monthly_shipping_budget'] = pd.to_numeric(


In [1057]:
#Changing the money from object to float
customers['monthly_shipping_budget'] = pd.to_numeric(customers['monthly_shipping_budget'])

C:\Users\E1023380\AppData\Local\Temp\ipykernel_30760\52773667.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  customers['monthly_shipping_budget'] = pd.to_numeric(customers['monthly_shipping_budget'])


In [1058]:
customers.monthly_shipping_budget

0         3530.20
1         1555.50
2        13767.67
3        10034.40
4         7054.38
           ...   
99995    78517.63
99996     7369.63
99997     9942.18
99998      838.25
99999    69674.92
Name: monthly_shipping_budget, Length: 100000, dtype: float64

In [1059]:
customers.columns

Index(['customer_id', 'customer_name', 'customer_type', 'province', 'city',
       'registration_date', 'monthly_shipping_budget'],
      dtype='object')

In [1060]:
customers.customer_name.unique()

array(['Sipho Adams', 'Amanda Maseko', 'Karabo Mkhize', 'Bongani Sithole',
       'Bongani Dlamini', 'Nokuthula Naidoo', 'Sipho Maseko',
       'Lindelwa Khumalo', 'Mpho Molefe', 'Sipho Mabena',
       'Busisiwe Mabena', 'Dumisani Ngcobo', 'Siyabonga Khumalo',
       'Amanda Cele', 'Lindelwa Mabena', 'Amanda Mokoena',
       'Themba Naidoo', 'Nomsa Van Wyk', 'Mandla Mthembu',
       'Precious Ndlovu', 'Themba Mkhize', 'Zanele Williams',
       'Ayanda Mthembu', 'Phumzile Modise', 'Karabo Mthembu',
       'Bongani Ngcobo', 'Mandla Ngcobo', 'Busisiwe Sithole',
       'Precious Naidoo', 'Precious Molefe', 'Mpho Moyo', 'Sipho Nkosi',
       'Busisiwe Van Wyk', 'Kabelo Botha', 'Lerato Sithole',
       'Nokuthula Mokoena', 'Mandla Moyo', 'Lwazi Mkhize', 'Tshepo Zulu',
       'Ayanda Khumalo', 'Siyabonga Mahlangu', 'Lindelwa Pillay',
       'Sibusiso Mabena', 'Lerato Ndlovu', 'Dumisani Williams',
       'Precious Zulu', 'Kabelo Mokoena', 'Karabo Jacobs', 'Amanda Adams',
       'Siyabonga Both

In [1061]:
customers.customer_type.unique()

array(['Business', 'Individual', 'Enterprise'], dtype=object)

In [1062]:
customers.province.unique()

array(['Gauteng', 'Limpopo', 'KwaZulu-Natal', 'Eastern Cape',
       'Western Cape', 'North West', 'Free State', ' Western Cape ',
       ' Gauteng ', 'Mpumalanga', 'Northern Cape', ' Eastern Cape ',
       'gauteng', 'KWAZULU-NATAL', 'GAUTENG', 'western cape',
       'EASTERN CAPE', 'MPUMALANGA', ' Limpopo ', ' KwaZulu-Natal ',
       'eastern cape', 'kwazulu-natal', 'FREE STATE', 'north west',
       'WESTERN CAPE', 'LIMPOPO', 'free state', ' Mpumalanga ', 'limpopo',
       ' Free State ', 'NORTH WEST', 'NORTHERN CAPE', ' North West ',
       'northern cape', 'mpumalanga', ' Northern Cape '], dtype=object)

In [1063]:
#Fixing incosistence
customers.province= customers.province.str.strip()
customers.province= customers.province.str.title()


C:\Users\E1023380\AppData\Local\Temp\ipykernel_30760\446329367.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  customers.province= customers.province.str.strip()
C:\Users\E1023380\AppData\Local\Temp\ipykernel_30760\446329367.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  customers.province= customers.province.str.title()


In [1064]:
customers.city.unique() 

array(['Centurion', 'Johannesburg', 'Polokwane', 'Richards Bay',
       'East London', 'Pretoria', 'Gqeberha', 'Umhlanga', 'Durban',
       'Paarl', 'Newcastle', nan, 'Pietermaritzburg', 'Midrand',
       'Grahamstown', 'Klerksdorp', 'Mthatha', 'Sandton', 'Cape Town',
       'Soweto', 'Bloemfontein', 'Stellenbosch', 'Welkom', 'George',
       'Bellville', 'Potchefstroom', 'Kroonstad', 'Worcester', 'Mahikeng',
       'Tzaneen', 'Middelburg', 'Nelspruit', 'Kuruman', 'Mbombela',
       'Thohoyandou', 'Witbank', 'Kimberley', 'Upington', 'Rustenburg'],
      dtype=object)

In [1065]:
customers.registration_date.unique()

<DatetimeArray>
['2024-10-13 00:00:00', '2022-01-26 00:00:00', '2019-03-04 00:00:00',
 '2021-06-30 00:00:00', '2026-03-28 00:00:00', '2024-07-06 00:00:00',
 '2018-09-30 00:00:00', '2024-04-16 00:00:00', '2025-02-19 00:00:00',
 '2024-05-11 00:00:00',
 ...
 '2018-04-21 00:00:00', '2024-03-18 00:00:00', '2026-06-05 00:00:00',
 '2022-03-30 00:00:00', '2019-08-03 00:00:00', '2019-04-29 00:00:00',
 '2020-06-29 00:00:00', '2025-05-24 00:00:00', '2021-04-16 00:00:00',
 '2023-05-26 00:00:00']
Length: 3102, dtype: datetime64[ns]

In [1066]:
customers.monthly_shipping_budget.unique()

array([ 3530.2 ,  1555.5 , 13767.67, ...,  9942.18,   838.25, 69674.92],
      shape=(97684,))

In [1067]:
customers['monthly_shipping_budget'].unique

<bound method Series.unique of 0         3530.20
1         1555.50
2        13767.67
3        10034.40
4         7054.38
           ...   
99995    78517.63
99996     7369.63
99997     9942.18
99998      838.25
99999    69674.92
Name: monthly_shipping_budget, Length: 100000, dtype: float64>

In [1068]:
#Checking for missing values
customers.isnull().sum()

customer_id                   0
customer_name                 0
customer_type                 0
province                      0
city                       1028
registration_date             0
monthly_shipping_budget     989
dtype: int64

In [1069]:
(customers.isna().sum() / len(customers)) * 100

customer_id                0.000
customer_name              0.000
customer_type              0.000
province                   0.000
city                       1.028
registration_date          0.000
monthly_shipping_budget    0.989
dtype: float64

In [1070]:
customers[customers['monthly_shipping_budget'].isna()]

,customer_id,customer_name,customer_type,province,city,registration_date,monthly_shipping_budget
13,C000014,Amanda Cele,Individual,Limpopo,Polokwane,2024-02-01,NaN
85,C000086,Lindelwa Nkosi,Individual,Kwazulu-Natal,Newcastle,2024-11-13,NaN
202,C000203,Themba Mkhize,Business,Limpopo,Thohoyandou,2025-01-10,NaN
236,C000237,Karabo Mabena,Business,Gauteng,Centurion,2019-07-28,NaN
263,C000264,Phumzile Naidoo,Business,Gauteng,Johannesburg,2018-07-21,NaN
...,...,...,...,...,...,...,...
98827,C098828,Ayanda Zulu,Enterprise,Free State,Kroonstad,2020-07-09,NaN
98997,C098998,Siyabonga Pillay,Business,Eastern Cape,Gqeberha,2021-12-10,NaN
99405,C099406,Kagiso Mokoena,Individual,Western Cape,Paarl,2019-01-18,NaN
99540,C099541,Mandla Ngcobo,Individual,Kwazulu-Natal,Umhlanga,2022-02-20,NaN


In [1071]:
customers['monthly_shipping_budget'].isna().sum()

np.int64(989)

In [1072]:
customers[customers['city'].isna()]["city"]

14       NaN
160      NaN
251      NaN
290      NaN
328      NaN
        ... 
99526    NaN
99577    NaN
99603    NaN
99830    NaN
99841    NaN
Name: city, Length: 1028, dtype: object

In [1073]:
customers['city'].isna().sum()

np.int64(1028)

In [1074]:
#Checking the Pronvices in which province has cities that has missing value 
customers.loc[customers['city'].isna(), "province"].value_counts()

province
Gauteng          301
Kwazulu-Natal    208
Western Cape     189
Eastern Cape     106
Free State        60
Limpopo           56
Mpumalanga        54
North West        36
Northern Cape     18
Name: count, dtype: int64

In [1075]:
customers['city'] = customers['city'].fillna('Unknown')

C:\Users\E1023380\AppData\Local\Temp\ipykernel_30760\4010663513.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  customers['city'] = customers['city'].fillna('Unknown')


In [1076]:
customers.loc[customers['monthly_shipping_budget'].isna(), "city"].value_counts()

city
Johannesburg        56
Sandton             49
Centurion           46
Midrand             44
Richards Bay        43
Soweto              42
Pietermaritzburg    42
Mthatha             38
Pretoria            37
Bellville           36
Gqeberha            33
George              32
Newcastle           31
Stellenbosch        29
Bloemfontein        29
Paarl               29
Umhlanga            29
Worcester           29
Durban              27
Polokwane           26
Cape Town           25
Thohoyandou         22
Tzaneen             21
Kroonstad           21
Grahamstown         20
Nelspruit           16
East London         16
Welkom              14
Witbank             14
Klerksdorp          12
Rustenburg          12
Unknown             11
Mbombela            11
Potchefstroom        9
Mahikeng             9
Middelburg           8
Kuruman              8
Upington             7
Kimberley            6
Name: count, dtype: int64

In [1077]:
customers['monthly_shipping_budget'] = customers['monthly_shipping_budget'].fillna(
customers['monthly_shipping_budget'].median())

C:\Users\E1023380\AppData\Local\Temp\ipykernel_30760\3097473623.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  customers['monthly_shipping_budget'] = customers['monthly_shipping_budget'].fillna(


In [1078]:
customers.groupby("city")["monthly_shipping_budget"].median()

city
Bellville           14747.090
Bloemfontein        14514.720
Cape Town           14944.890
Centurion           15164.880
Durban              15059.575
East London         15326.425
George              14573.205
Gqeberha            14944.890
Grahamstown         15170.260
Johannesburg        14944.890
Kimberley           14579.660
Klerksdorp          13989.130
Kroonstad           15485.175
Kuruman             14693.720
Mahikeng            15193.880
Mbombela            14409.735
Middelburg          14944.890
Midrand             14944.890
Mthatha             14779.860
Nelspruit           14998.120
Newcastle           15136.870
Paarl               15087.915
Pietermaritzburg    14944.890
Polokwane           15612.720
Potchefstroom       14423.190
Pretoria            14944.890
Richards Bay        14555.900
Rustenburg          14902.880
Sandton             15180.260
Soweto              14944.890
Stellenbosch        14944.890
Thohoyandou         14712.870
Tzaneen             14944.890
Umhla

In [1079]:
city_counts = customers.groupby(["province", "city"]).size().reset_index(name= "Customer_count")
city_counts

,province,city,Customer_count
0,Eastern Cape,East London,2478
1,Eastern Cape,Gqeberha,2408
2,Eastern Cape,Grahamstown,2605
3,Eastern Cape,Mthatha,2462
4,Eastern Cape,Unknown,106
5,Free State,Bloemfontein,2020
6,Free State,Kroonstad,1980
7,Free State,Unknown,60
8,Free State,Welkom,2035
9,Gauteng,Centurion,5073


# Insepecting Shipments and Cleaning 

In [1080]:
import pandas as pd
shipments = pd.read_csv("supplyguard_data/shipments.csv")
shipments

,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,priority
0,S000000001,C063536,W00238,2025-12-14,Express,Road,11.97,10832.99,926.17,Low
1,S000000002,C054654,W00230,2025-03-21,Express,Road,73.29,90025.97,63.22,Medium
2,S000000003,C075489,W00180,2026-06-23,Bulk,Road,90.70,73339.17,374.86,Critical
3,S000000004,C041283,W00029,2026-07-21,Same Day,Air,13.26,11410.73,148.44,Medium
4,S000000005,C019038,W00013,2025-07-15,Express,Road,36.98,23529.59,61.17,Low
...,...,...,...,...,...,...,...,...,...,...
1002995,S000387159,C079142,W00026,2025-03-12,Standard,Road,11.18,13327.15,363.99,Medium
1002996,S000211228,C058421,W00055,2025-02-01,Bulk,Road,2.09,882.78,234.72,Low
1002997,S000229470,C042115,W00046,2025-11-04,Standard,Road,44.40,9095.88,17.82,Medium
1002998,S000003812,C037869,W00115,2026-04-05,Standard,Road,34.45,51389.76,330.49,Medium


In [1081]:
shipments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1003000 entries, 0 to 1002999
Data columns (total 10 columns):
 #   Column              Non-Null Count    Dtype  
---  ------              --------------    -----  
 0   shipment_id         1003000 non-null  object 
 1   customer_id         1003000 non-null  object 
 2   warehouse_id        1003000 non-null  object 
 3   shipment_date       1003000 non-null  object 
 4   shipment_type       1003000 non-null  object 
 5   delivery_method     1003000 non-null  object 
 6   weight_kg           1003000 non-null  float64
 7   declared_value_zar  992909 non-null   object 
 8   distance_km         992910 non-null   float64
 9   priority            1003000 non-null  object 
dtypes: float64(2), object(8)
memory usage: 76.5+ MB


In [1082]:
shipments.duplicated()

0          False
1          False
2          False
3          False
4          False
           ...  
1002995     True
1002996     True
1002997     True
1002998     True
1002999     True
Length: 1003000, dtype: bool

In [1083]:
shipments[shipments.duplicated() == True]

,shipment_id,customer_id,warehouse_id,shipment_date,shipment_type,delivery_method,weight_kg,declared_value_zar,distance_km,priority
1000000,S000910392,C010270,W00225,2025-08-29,Standard,Road,29.49,36820.7,171.15,Medium
1000001,S000521922,C042237,W00212,2026-04-21,Standard,Road,2.91,157.86,115.51,Medium
1000002,S000085994,C051034,W00140,2025-11-01,Express,Road,86.49,109568.46,84.32,High
1000003,S000316326,C007728,W00218,2025-05-13,Standard,Courier,11.68,9564.37,13.86,Medium
1000004,S000374572,C049758,W00042,2025-02-14,Express,Road,290.74,50297.92,1856.51,Medium
...,...,...,...,...,...,...,...,...,...,...
1002995,S000387159,C079142,W00026,2025-03-12,Standard,Road,11.18,13327.15,363.99,Medium
1002996,S000211228,C058421,W00055,2025-02-01,Bulk,Road,2.09,882.78,234.72,Low
1002997,S000229470,C042115,W00046,2025-11-04,Standard,Road,44.40,9095.88,17.82,Medium
1002998,S000003812,C037869,W00115,2026-04-05,Standard,Road,34.45,51389.76,330.49,Medium


In [1084]:
shipments = shipments.drop_duplicates()

In [1085]:
shipments['shipment_date'] = pd.to_datetime(shipments['shipment_date'])

C:\Users\E1023380\AppData\Local\Temp\ipykernel_30760\3395169456.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  shipments['shipment_date'] = pd.to_datetime(shipments['shipment_date'])


In [1086]:
shipments['declared_value_zar'] = shipments['declared_value_zar'].str.replace(",", "")
shipments['declared_value_zar'] = shipments['declared_value_zar'].str.replace(" ", "")
shipments['declared_value_zar'] = shipments['declared_value_zar'].astype(float)

C:\Users\E1023380\AppData\Local\Temp\ipykernel_30760\1826243068.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  shipments['declared_value_zar'] = shipments['declared_value_zar'].str.replace(",", "")
C:\Users\E1023380\AppData\Local\Temp\ipykernel_30760\1826243068.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  shipments['declared_value_zar'] = shipments['declared_value_zar'].str.replace(" ", "")
C:\Users\E1023380\AppData\Local\Temp\ipykernel_30760\1826243068.py:3: SettingWithCopyWarning: 
A value is 

In [1087]:
shipments.columns

Index(['shipment_id', 'customer_id', 'warehouse_id', 'shipment_date',
       'shipment_type', 'delivery_method', 'weight_kg', 'declared_value_zar',
       'distance_km', 'priority'],
      dtype='object')

In [1088]:
shipments.shipment_type.unique()

array(['Express', 'Bulk', 'Same Day', 'Standard', 'International'],
      dtype=object)

In [1089]:
shipments.delivery_method.unique()

array(['Road', 'Air', 'Freight', 'Courier'], dtype=object)

In [1090]:
shipments.weight_kg.unique()

array([ 11.97,  73.29,  90.7 , ..., 165.71, 365.76, 396.94],
      shape=(37612,))

In [1091]:
shipments.declared_value_zar.unique()

array([10832.99, 90025.97, 73339.17, ...,  9506.09, 14523.73, 11580.34],
      shape=(876828,))

In [1092]:
shipments.distance_km.unique()

array([ 926.17,   63.22,  374.86, ..., 2348.77, 2092.64, 1583.85],
      shape=(150660,))

In [1093]:
shipments.priority.unique()

array(['Low', 'Medium', 'Critical', 'High', 'MEDIUM', 'medium', 'high',
       'LOW', 'HIGH', ' Medium ', ' Low ', 'critical', ' High ',
       'CRITICAL', 'low', ' Critical '], dtype=object)

In [1094]:
shipments.priority= shipments.priority.str.strip()
shipments.priority= shipments.priority.str.title()

C:\Users\E1023380\AppData\Local\Temp\ipykernel_30760\113188996.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  shipments.priority= shipments.priority.str.strip()
C:\Users\E1023380\AppData\Local\Temp\ipykernel_30760\113188996.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  shipments.priority= shipments.priority.str.title()


In [1095]:
shipments.isna().sum()

shipment_id               0
customer_id               0
warehouse_id              0
shipment_date             0
shipment_type             0
delivery_method           0
weight_kg                 0
declared_value_zar    10062
distance_km           10064
priority                  0
dtype: int64

In [1096]:
(shipments.isna().sum() / len(shipments)) * 100

shipment_id           0.0000
customer_id           0.0000
warehouse_id          0.0000
shipment_date         0.0000
shipment_type         0.0000
delivery_method       0.0000
weight_kg             0.0000
declared_value_zar    1.0062
distance_km           1.0064
priority              0.0000
dtype: float64

In [1097]:
shipments[['declared_value_zar', 'distance_km']].isna().mean() * 100

declared_value_zar    1.0062
distance_km           1.0064
dtype: float64

In [1098]:
shipments.loc[shipments['declared_value_zar'].isna(), "shipment_type"].value_counts()

shipment_type
Standard         5005
Express          2009
Bulk             1479
Same Day         1065
International     504
Name: count, dtype: int64

In [1099]:
shipments['declared_value_zar'].isna().sum()

np.int64(10062)

In [1100]:
shipments[shipments['declared_value_zar'].isna()]['declared_value_zar']

34       NaN
562      NaN
785      NaN
954      NaN
1071     NaN
          ..
999614   NaN
999630   NaN
999671   NaN
999744   NaN
999875   NaN
Name: declared_value_zar, Length: 10062, dtype: float64

In [1101]:
shipments['declared_value_zar'] = shipments['declared_value_zar'].fillna(
shipments['declared_value_zar'].median())

C:\Users\E1023380\AppData\Local\Temp\ipykernel_30760\885146159.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  shipments['declared_value_zar'] = shipments['declared_value_zar'].fillna(


In [1102]:
shipments.loc[shipments['distance_km'].isna(), "priority"].value_counts()

priority
Medium      4987
High        2546
Low         2010
Critical     521
Name: count, dtype: int64

In [1103]:
shipments[shipments['distance_km'].isna()]['distance_km']

9        NaN
161      NaN
340      NaN
546      NaN
624      NaN
          ..
999503   NaN
999614   NaN
999761   NaN
999851   NaN
999927   NaN
Name: distance_km, Length: 10064, dtype: float64

In [1104]:
shipments.loc[shipments['declared_value_zar'].isna(), "distance_km"].value_counts() 

Series([], Name: count, dtype: int64)

In [1105]:
shipments['distance_km'] = shipments['distance_km'].fillna(
shipments['distance_km'].median())

C:\Users\E1023380\AppData\Local\Temp\ipykernel_30760\1370765055.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  shipments['distance_km'] = shipments['distance_km'].fillna(


# Inspecting  Vehicle and Cleaning data

In [1106]:
import pandas as pd
vehicles = pd.read_csv("supplyguard_data/vehicles.csv")
vehicles

,vehicle_id,vehicle_type,vehicle_age_years,capacity_kg,fuel_type,maintenance_score,current_mileage_km
0,V000001,Medium Truck,1,8000,Diesel,85.06,193997.0
1,V000002,Medium Truck,5,8000,Diesel,83.39,72050.0
2,V000003,Medium Truck,5,8000,Diesel,68.78,1000.0
3,V000004,Motorbike,11,50,Petrol,66.61,206076.0
4,V000005,Van,4,1000,Petrol,89.17,119600.0
...,...,...,...,...,...,...,...
14995,V014996,Medium Truck,2,8000,Diesel,90.91,245536.0
14996,V014997,Medium Truck,6,8000,Diesel,100.00,201289.0
14997,V014998,Medium Truck,12,8000,Diesel,77.80,91515.0
14998,V014999,Medium Truck,14,8000,Diesel,73.72,105680.0


In [1107]:
vehicles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   vehicle_id          15000 non-null  object 
 1   vehicle_type        15000 non-null  object 
 2   vehicle_age_years   15000 non-null  int64  
 3   capacity_kg         15000 non-null  int64  
 4   fuel_type           15000 non-null  object 
 5   maintenance_score   15000 non-null  float64
 6   current_mileage_km  15000 non-null  float64
dtypes: float64(2), int64(2), object(3)
memory usage: 820.4+ KB


In [1108]:
vehicles.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...  
14995    False
14996    False
14997    False
14998    False
14999    False
Length: 15000, dtype: bool

In [1109]:
vehicles[vehicles.duplicated() == True]

,vehicle_id,vehicle_type,vehicle_age_years,capacity_kg,fuel_type,maintenance_score,current_mileage_km


In [1110]:
vehicles.columns

Index(['vehicle_id', 'vehicle_type', 'vehicle_age_years', 'capacity_kg',
       'fuel_type', 'maintenance_score', 'current_mileage_km'],
      dtype='object')

In [1111]:
vehicles.vehicle_type.unique()

array(['Medium Truck', 'Motorbike', 'Van', 'Light Truck', 'Heavy Truck'],
      dtype=object)

In [1112]:
vehicles.vehicle_age_years.unique()

array([ 1,  5, 11,  4,  0,  7,  6, 14,  9, 10, 12, 13,  8,  3,  2])

In [1113]:
vehicles.capacity_kg.unique()

array([ 8000,    50,  1000,  3500, 20000])

In [1114]:
vehicles.fuel_type.unique()

array(['Diesel', 'Petrol'], dtype=object)

In [1115]:
vehicles.maintenance_score.unique()

array([85.06, 83.39, 68.78, ..., 61.34, 61.1 , 59.42], shape=(4117,))

In [1116]:
vehicles.current_mileage_km.unique()

array([193997.,  72050.,   1000., ...,  91515., 105680., 155478.],
      shape=(14298,))

In [1117]:
print(vehicles["current_mileage_km"].head(10).to_list())

[193997.0, 72050.0, 1000.0, 206076.0, 119600.0, 163284.0, 154709.0, 23537.0, 337431.0, 172167.0]


In [1118]:
vehicles.isna().sum()

vehicle_id            0
vehicle_type          0
vehicle_age_years     0
capacity_kg           0
fuel_type             0
maintenance_score     0
current_mileage_km    0
dtype: int64

# Insepecting exchange rate and cleaning data

In [1119]:
import pandas as pd
exchange_rates = pd.read_csv("supplyguard_data/exchange_rates.csv")
exchange_rates 

,date,currency,zar_rate
0,2025-01-01,USD,18.1591
1,2025-01-01,GBP,23.2890
2,2025-01-01,EUR,21.0701
3,2025-01-01,AUD,11.7025
4,2025-01-02,USD,18.3837
...,...,...,...
2303,2026-07-30,AUD,11.8109
2304,2026-07-31,USD,18.4465
2305,2026-07-31,GBP,23.5821
2306,2026-07-31,EUR,20.8384


In [1120]:
exchange_rates.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2308 entries, 0 to 2307
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   date      2308 non-null   object 
 1   currency  2308 non-null   object 
 2   zar_rate  2308 non-null   float64
dtypes: float64(1), object(2)
memory usage: 54.2+ KB


In [1121]:
exchange_rates.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
2303    False
2304    False
2305    False
2306    False
2307    False
Length: 2308, dtype: bool

In [1122]:
exchange_rates[exchange_rates.duplicated() == True]

,date,currency,zar_rate


In [1123]:
exchange_rates.columns

Index(['date', 'currency', 'zar_rate'], dtype='object')

In [1124]:
exchange_rates.date.unique()

array(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
       '2025-01-05', '2025-01-06', '2025-01-07', '2025-01-08',
       '2025-01-09', '2025-01-10', '2025-01-11', '2025-01-12',
       '2025-01-13', '2025-01-14', '2025-01-15', '2025-01-16',
       '2025-01-17', '2025-01-18', '2025-01-19', '2025-01-20',
       '2025-01-21', '2025-01-22', '2025-01-23', '2025-01-24',
       '2025-01-25', '2025-01-26', '2025-01-27', '2025-01-28',
       '2025-01-29', '2025-01-30', '2025-01-31', '2025-02-01',
       '2025-02-02', '2025-02-03', '2025-02-04', '2025-02-05',
       '2025-02-06', '2025-02-07', '2025-02-08', '2025-02-09',
       '2025-02-10', '2025-02-11', '2025-02-12', '2025-02-13',
       '2025-02-14', '2025-02-15', '2025-02-16', '2025-02-17',
       '2025-02-18', '2025-02-19', '2025-02-20', '2025-02-21',
       '2025-02-22', '2025-02-23', '2025-02-24', '2025-02-25',
       '2025-02-26', '2025-02-27', '2025-02-28', '2025-03-01',
       '2025-03-02', '2025-03-03', '2025-03-04', '2025-

In [1125]:
exchange_rates['date'] = pd.to_datetime(exchange_rates['date'])

In [1126]:
exchange_rates.currency.unique()

array(['USD', 'GBP', 'EUR', 'AUD'], dtype=object)

In [1127]:
exchange_rates['zar_rate'] = pd.to_numeric(exchange_rates['zar_rate'])

In [1128]:
exchange_rates.isna().sum()

date        0
currency    0
zar_rate    0
dtype: int64

# Inspecting Deliveries and Cleaning data

In [1129]:
import pandas as pd
deliveries = pd.read_csv("supplyguard_data/deliveries.csv")
deliveries 

,delivery_id,shipment_id,driver_id,vehicle_id,delivery_date,delivery_status,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour
0,DL000000001,S000000001,D002400,V013743,2025-12-16,Delivered Late,16.60,935.04,2504.92,2.30,3,9
1,DL000000002,S000000002,D006019,V012835,2025-03-22,Delivered,1.06,57.08,115.77,3.30,1,12
2,DL000000003,S000000003,D006461,V000347,2026-06-26,Delivered,7.56,402.48,891.87,4.09,1,19
3,DL000000004,S000000004,D007914,V010330,2026-07-21,Delivered,3.35,147.70,609.51,3.68,1,16
4,DL000000005,S000000005,D005693,V011795,2025-07-16,Delivered,1.81,54.77,122.58,4.18,1,17
...,...,...,...,...,...,...,...,...,...,...,...,...
999995,DL000999996,S000999996,D005627,V000427,2025-07-08,Delivered,1.33,64.93,202.73,4.04,1,6
999996,DL000999997,S000999997,D001882,V006763,2026-05-05,Delivered,3.63,261.61,946.81,4.29,2,16
999997,DL000999998,S000999998,D008550,V010821,2025-12-17,Delivered,2.01,100.67,371.75,4.38,1,13
999998,DL000999999,S000999999,D008389,V004063,2026-03-04,Delivered,1.17,58.36,157.25,4.64,1,5


In [ ]:
deliveries.info()

In [1131]:
deliveries.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...  
999995    False
999996    False
999997    False
999998    False
999999    False
Length: 1000000, dtype: bool

In [1132]:
deliveries[deliveries.duplicated() == True]

,delivery_id,shipment_id,driver_id,vehicle_id,delivery_date,delivery_status,delivery_duration_hours,delivery_distance_km,fuel_cost_zar,customer_rating,attempt_number,delivery_hour


In [1133]:
deliveries.columns

Index(['delivery_id', 'shipment_id', 'driver_id', 'vehicle_id',
       'delivery_date', 'delivery_status', 'delivery_duration_hours',
       'delivery_distance_km', 'fuel_cost_zar', 'customer_rating',
       'attempt_number', 'delivery_hour'],
      dtype='object')

In [1134]:
deliveries.delivery_date.unique()

array(['2025-12-16', '2025-03-22', '2026-06-26', '2026-07-21',
       '2025-07-16', '2026-04-29', '2025-12-10', '2025-07-17',
       '2025-05-11', '2026-03-13', '2026-03-24', '2026-07-08',
       '2025-09-24', '2026-07-28', '2026-03-27', '2026-07-15',
       '2026-04-14', '2025-01-23', '2026-03-29', '2025-12-20',
       '2025-06-14', '2026-01-09', '2025-04-01', '2026-03-14',
       '2025-08-24', '2026-02-03', '2026-05-02', '2025-01-03',
       '2025-12-26', '2025-03-20', '2026-05-10', '2026-03-22',
       '2025-09-02', '2026-03-26', '2025-10-05', '2025-03-10',
       '2026-03-18', '2025-03-25', '2026-05-20', '2026-05-19',
       '2025-03-24', '2025-01-28', '2026-03-06', '2025-01-05',
       '2025-01-07', '2026-04-11', '2026-04-21', '2026-04-27',
       '2025-10-06', '2025-04-12', '2026-02-05', '2025-11-06',
       '2026-04-06', '2025-07-08', '2026-03-11', '2025-11-11',
       '2026-01-17', '2025-04-16', '2025-10-07', '2025-07-28',
       '2026-08-01', '2026-04-22', '2025-12-29', '2025-

In [1135]:
deliveries['delivery_date'] = pd.to_datetime(deliveries['delivery_date'])

In [1136]:
deliveries.delivery_status.unique()

array(['Delivered Late', 'Delivered', 'Delayed', 'DELIVERED', 'delayed',
       'delivered', 'delivered late', ' Delivered ', ' Delivered Late ',
       'DELIVERED LATE', ' Delayed ', 'DELAYED'], dtype=object)

In [1137]:
deliveries.delivery_status= deliveries.delivery_status.str.strip()
deliveries.delivery_status= deliveries.delivery_status.str.title()

In [1138]:
deliveries.delivery_duration_hours.unique()

array([16.6 ,  1.06,  7.56, ..., 41.67, 63.06, 61.21], shape=(6451,))

In [1139]:
deliveries.delivery_distance_km.unique()

array([ 935.04,   57.08,  402.48, ..., 1737.04, 1762.13, 2167.17],
      shape=(162063,))

In [1140]:
deliveries.fuel_cost_zar.unique()

array([2504.92,  115.77,  891.87, ..., 2315.06, 1270.61, 2509.55],
      shape=(332709,))

In [1141]:
deliveries.customer_rating.unique()

array([2.3 , 3.3 , 4.09, 3.68, 4.18, 3.52, 4.  , 2.84, 4.72, 3.99, 4.06,
       4.47, 4.62, 3.75, 4.75, 4.12, 2.56, 3.91, 5.  , 4.66, 3.73, 4.98,
       4.25, 1.62, 3.92, 4.78, 4.71, 3.97, 1.  , 3.15, 4.17, 3.93, 4.85,
       4.32, 4.39, 2.94, 4.22, 4.73, 4.13, 4.86, 3.54, 4.69, 1.48, 3.16,
       2.02, 3.72, 3.38, 2.91, 3.86, 1.86, 3.74, 4.95, 4.16, 3.13, 3.37,
       4.02, 2.25, 4.03, 3.49, 1.88, 4.8 , 2.68, 3.64, 4.64, 4.23, 3.35,
       4.5 , 4.55, 4.59, 3.79, 3.89, 4.11, 4.76, 4.94, 3.51, 4.37,  nan,
       4.56, 3.98, 4.24, 4.48, 3.1 , 4.68, 3.48, 4.19, 4.6 , 4.57, 4.27,
       4.49, 3.53, 3.94, 2.41, 4.2 , 4.21, 4.42, 2.55, 3.58, 4.87, 4.65,
       3.67, 4.28, 3.95, 2.85, 4.33, 4.97, 4.99, 4.04, 3.25, 2.18, 1.76,
       3.85, 3.29, 3.77, 3.23, 1.65, 4.29, 4.4 , 3.87, 4.79, 4.51, 4.26,
       3.84, 3.07, 4.41, 3.96, 3.88, 1.16, 2.64, 3.69, 3.21, 2.75, 3.76,
       2.28, 4.77, 4.31, 4.35, 2.59, 3.63, 4.08, 1.2 , 3.9 , 2.66, 3.8 ,
       3.06, 3.6 , 4.89, 4.38, 3.  , 2.52, 4.14, 2.

In [1142]:
deliveries.attempt_number.unique()

array([3, 1, 2])

In [1143]:
deliveries.delivery_hour.unique()

array([ 9, 12, 19, 16, 17, 18, 14, 20, 13, 21, 10,  6,  5,  8, 15, 22, 11,
        7])

In [1144]:
deliveries.isnull().sum()

delivery_id                   0
shipment_id                   0
driver_id                     0
vehicle_id                    0
delivery_date                 0
delivery_status               0
delivery_duration_hours       0
delivery_distance_km          0
fuel_cost_zar              9869
customer_rating            9984
attempt_number                0
delivery_hour                 0
dtype: int64

In [ ]:
deliveries.groupby("delivery_status")["fuel_cost_zar"].median()

In [1146]:
deliveries["fuel_cost_zar"] = deliveries["fuel_cost_zar"].fillna(
deliveries.groupby("delivery_status")["fuel_cost_zar"].transform("median"))

In [1147]:
deliveries["fuel_cost_zar"].isna().sum()

np.int64(0)

In [1148]:
deliveries["fuel_cost_zar"] = deliveries["fuel_cost_zar"].fillna(deliveries["fuel_cost_zar"].median())

In [ ]:
deliveries["customer_rating"].describe()
deliveries["customer_rating"].value_counts().sort_index()

In [1188]:
deliveries["customer_rating"] = deliveries["customer_rating"].fillna(deliveries["customer_rating"].median())

# Inspecting Drivers and Cleaning Data

In [1149]:
import pandas as pd
drivers = pd.read_csv("supplyguard_data/drivers.csv")
drivers

,driver_id,driver_name,age,experience_years,license_type,employment_type,home_province,performance_rating
0,D000001,Dumisani Molefe,47,34,Code 10,Contract,North West,3.51
1,D000002,Mpho Modise,59,25,Code 10,Contract,Western Cape,3.28
2,D000003,Themba Naidoo,37,6,Code 14,Permanent,Free State,4.59
3,D000004,Tshepo Dlamini,38,23,Code 8,Contract,Western Cape,4.31
4,D000005,Nokuthula Ndlovu,50,3,Code 8,Owner Driver,Mpumalanga,3.80
...,...,...,...,...,...,...,...,...
9995,D009996,Lindelwa Naidoo,49,8,Code 14,Permanent,Northern Cape,4.18
9996,D009997,Nandi Sithole,58,32,Code 14,Contract,KwaZulu-Natal,5.00
9997,D009998,Kabelo Adams,47,8,Code 10,Permanent,Gauteng,4.43
9998,D009999,Amanda Mahlangu,37,23,Code 14,Contract,KwaZulu-Natal,4.37


In [1150]:
drivers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   driver_id           10000 non-null  object 
 1   driver_name         10000 non-null  object 
 2   age                 10000 non-null  int64  
 3   experience_years    10000 non-null  int64  
 4   license_type        10000 non-null  object 
 5   employment_type     10000 non-null  object 
 6   home_province       10000 non-null  object 
 7   performance_rating  10000 non-null  float64
dtypes: float64(1), int64(2), object(5)
memory usage: 625.1+ KB


In [1151]:
drivers.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

In [1152]:
drivers[drivers.duplicated() == True]

,driver_id,driver_name,age,experience_years,license_type,employment_type,home_province,performance_rating


In [1153]:
drivers.columns

Index(['driver_id', 'driver_name', 'age', 'experience_years', 'license_type',
       'employment_type', 'home_province', 'performance_rating'],
      dtype='object')

In [1154]:
drivers.driver_name.unique()

array(['Dumisani Molefe', 'Mpho Modise', 'Themba Naidoo',
       'Tshepo Dlamini', 'Nokuthula Ndlovu', 'Lerato Moyo',
       'Siyabonga Khumalo', 'Lwazi Botha', 'Thabo Mthembu',
       'Zanele Jacobs', 'Siyabonga Naidoo', 'Themba Mokoena',
       'Sipho Naidoo', 'Lerato Mkhize', 'Sibusiso Dlamini',
       'Lindelwa Botha', 'Kabelo Modise', 'Phumzile Naidoo',
       'Lerato Mabena', 'Karabo Modise', 'Busisiwe Modise',
       'Thabo Williams', 'Sibusiso Jacobs', 'Precious Nkosi',
       'Precious Mthembu', 'Nokuthula Nkosi', 'Amanda Botha',
       'Nomsa Molefe', 'Dumisani Jacobs', 'Sipho Adams', 'Lwazi Moyo',
       'Nokuthula Dlamini', 'Bongani Mkhize', 'Lindelwa Pillay',
       'Mpho Naidoo', 'Kagiso Maseko', 'Lwazi Mokoena', 'Mpho Sithole',
       'Sipho Zulu', 'Siyabonga Moyo', 'Phumzile Mkhize',
       'Sibusiso Botha', 'Nokuthula Naidoo', 'Lindelwa Dlamini',
       'Lwazi Maseko', 'Zanele Modise', 'Mandla Jacobs', 'Karabo Mthembu',
       'Zanele Mahlangu', 'Mandla Mahlangu', 'Sip

In [1155]:
drivers.age.unique()

array([47, 59, 37, 38, 50, 46, 45, 52, 41, 63, 55, 24, 40, 31, 26, 60, 39,
       23, 53, 57, 29, 61, 48, 56, 33, 54, 32, 65, 28, 35, 64, 42, 62, 43,
       30, 36, 34, 27, 58, 49, 51, 25, 44])

In [1156]:
drivers.experience_years.unique()

array([34, 25,  6, 23,  3, 22,  9, 20, 12, 21, 13, 30, 15, 17, 26,  4, 27,
        2, 16, 33, 24, 19,  5, 28,  8, 14, 11, 18,  1, 32, 29,  7, 31, 10])

In [1157]:
drivers.license_type.unique()

array(['Code 10', 'Code 14', 'Code 8'], dtype=object)

In [1158]:
drivers.employment_type.unique()

array(['Contract', 'Permanent', 'Owner Driver'], dtype=object)

In [1159]:
drivers.home_province.unique()

array(['North West', 'Western Cape', 'Free State', 'Mpumalanga',
       'Gauteng', 'Limpopo', 'Northern Cape', 'Eastern Cape',
       'KwaZulu-Natal'], dtype=object)

In [1160]:
drivers.performance_rating.unique()

array([3.51, 3.28, 4.59, 4.31, 3.8 , 4.6 , 3.36, 4.96, 3.71, 3.14, 4.66,
       4.93, 4.45, 3.24, 4.3 , 3.89, 3.46, 3.67, 3.73, 4.17, 4.1 , 3.4 ,
       4.22, 3.97, 3.1 , 3.94, 3.76, 4.89, 4.21, 2.67, 4.79, 3.12, 3.93,
       4.15, 3.75, 3.92, 3.01, 4.67, 3.13, 4.95, 4.29, 3.35, 3.17, 4.52,
       3.44, 4.02, 3.66, 4.4 , 3.65, 4.14, 3.52, 3.11, 3.45, 2.56, 4.61,
       3.88, 3.57, 4.03, 3.85, 3.37, 3.95, 4.35, 4.28, 4.27, 4.11, 3.83,
       4.34, 5.  , 3.81, 4.57, 3.55, 3.5 , 3.87, 4.63, 3.64, 3.34, 3.82,
       4.2 , 4.65, 3.43, 4.53, 3.06, 4.49, 4.  , 2.93, 4.05, 4.64, 4.56,
       4.12, 3.42, 4.07, 2.78, 4.08, 3.3 , 4.75, 4.06, 3.19, 4.62, 3.96,
       4.55, 3.7 , 4.13, 2.89, 3.62, 3.74, 3.78, 4.25, 3.26, 4.37, 4.69,
       4.23, 2.85, 3.79, 4.26, 4.47, 3.98, 3.33, 4.16, 3.99, 4.84, 3.56,
       3.77, 3.47, 4.72, 3.91, 3.61, 3.16, 3.69, 4.04, 4.42, 3.49, 2.82,
       4.09, 2.77, 4.39, 4.76, 4.01, 3.22, 3.53, 4.7 , 3.18, 4.46, 3.27,
       3.38, 4.18, 4.33, 3.68, 3.84, 3.63, 2.92, 4.

# Inspecting Warehouses and Cleaning Data

In [1161]:
import pandas as pd
warehouses = pd.read_csv("supplyguard_data/warehouses.csv")
warehouses

,warehouse_id,warehouse_name,city,province,warehouse_type,capacity_units
0,W00001,SupplyGuard Paarl Warehouse 1,Paarl,Western Cape,Distribution,79458
1,W00002,SupplyGuard Grahamstown Warehouse 2,Grahamstown,Eastern Cape,Cold Storage,74606
2,W00003,SupplyGuard Polokwane Warehouse 3,Polokwane,Limpopo,Cold Storage,106359
3,W00004,SupplyGuard Bloemfontein Warehouse 4,Bloemfontein,Free State,Regional,49522
4,W00005,SupplyGuard Rustenburg Warehouse 5,Rustenburg,North West,Fulfilment,240013
...,...,...,...,...,...,...
245,W00246,SupplyGuard Grahamstown Warehouse 246,Grahamstown,Eastern Cape,Cross-Dock,484898
246,W00247,SupplyGuard Polokwane Warehouse 247,Polokwane,Limpopo,Distribution,388641
247,W00248,SupplyGuard Thohoyandou Warehouse 248,Thohoyandou,Limpopo,Distribution,249748
248,W00249,SupplyGuard Johannesburg Warehouse 249,Johannesburg,Gauteng,Cold Storage,362366


In [1162]:
warehouses.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   warehouse_id    250 non-null    object
 1   warehouse_name  250 non-null    object
 2   city            250 non-null    object
 3   province        250 non-null    object
 4   warehouse_type  250 non-null    object
 5   capacity_units  250 non-null    int64 
dtypes: int64(1), object(5)
memory usage: 11.8+ KB


In [1163]:
warehouses.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...  
245    False
246    False
247    False
248    False
249    False
Length: 250, dtype: bool

In [1164]:
warehouses[warehouses.duplicated() == True]

,warehouse_id,warehouse_name,city,province,warehouse_type,capacity_units


In [1165]:
warehouses.columns

Index(['warehouse_id', 'warehouse_name', 'city', 'province', 'warehouse_type',
       'capacity_units'],
      dtype='object')

In [1166]:
warehouses.warehouse_name.unique()

array(['SupplyGuard Paarl Warehouse 1',
       'SupplyGuard Grahamstown Warehouse 2',
       'SupplyGuard Polokwane Warehouse 3',
       'SupplyGuard Bloemfontein Warehouse 4',
       'SupplyGuard Rustenburg Warehouse 5',
       'SupplyGuard Witbank Warehouse 6',
       'SupplyGuard Gqeberha Warehouse 7',
       'SupplyGuard Mbombela Warehouse 8',
       'SupplyGuard Mbombela Warehouse 9',
       'SupplyGuard Bloemfontein Warehouse 10',
       'SupplyGuard Kroonstad Warehouse 11',
       'SupplyGuard Kuruman Warehouse 12',
       'SupplyGuard Kimberley Warehouse 13',
       'SupplyGuard Mthatha Warehouse 14',
       'SupplyGuard Mahikeng Warehouse 15',
       'SupplyGuard Richards Bay Warehouse 16',
       'SupplyGuard Potchefstroom Warehouse 17',
       'SupplyGuard Nelspruit Warehouse 18',
       'SupplyGuard Polokwane Warehouse 19',
       'SupplyGuard Umhlanga Warehouse 20',
       'SupplyGuard Mbombela Warehouse 21',
       'SupplyGuard Polokwane Warehouse 22',
       'SupplyGuard

In [1167]:
warehouses.city.unique()

array(['Paarl', 'Grahamstown', 'Polokwane', 'Bloemfontein', 'Rustenburg',
       'Witbank', 'Gqeberha', 'Mbombela', 'Kroonstad', 'Kuruman',
       'Kimberley', 'Mthatha', 'Mahikeng', 'Richards Bay',
       'Potchefstroom', 'Nelspruit', 'Umhlanga', 'Upington',
       'Pietermaritzburg', 'George', 'Soweto', 'Centurion', 'Welkom',
       'Bellville', 'Cape Town', 'Klerksdorp', 'Newcastle', 'East London',
       'Sandton', 'Middelburg', 'Pretoria', 'Johannesburg', 'Thohoyandou',
       'Durban', 'Stellenbosch', 'Tzaneen', 'Midrand', 'Worcester'],
      dtype=object)

In [1168]:
warehouses.province.unique()

array(['Western Cape', 'Eastern Cape', 'Limpopo', 'Free State',
       'North West', 'Mpumalanga', 'Northern Cape', 'KwaZulu-Natal',
       'Gauteng'], dtype=object)

In [1169]:
warehouses.warehouse_type.unique()

array(['Distribution', 'Cold Storage', 'Regional', 'Fulfilment',
       'Cross-Dock'], dtype=object)

In [1170]:
warehouses.capacity_units.unique()

array([ 79458,  74606, 106359,  49522, 240013,  11370,  30469,  79188,
       137909, 240715, 225049, 231363, 456731,  27539, 232052, 320519,
       417720, 181633, 258591, 126015, 128814, 467183, 321836, 483191,
        77289, 484231, 287556, 418715, 480695, 131038, 380059, 190043,
       310979, 289148, 262485, 154402, 493911, 350774,  93380, 133075,
        81328, 123954, 153678, 230256, 264316, 183455, 123031, 139605,
       164041,  31544, 183752,  78119, 341463, 197192, 266078, 220420,
       319731, 247432, 227549, 312638,  35163, 215090, 118048, 483668,
        49663, 131191,  31135, 107085, 426343, 420059, 224122,  58586,
       386243, 378887,  76455, 316420,  25304, 344023, 125270, 424835,
       163719, 223531, 345143, 360585, 336858,  27130, 331731, 446419,
       295744, 386801, 182333, 216189,  99354, 295492, 346961, 155645,
       240890, 410769, 470356, 471285, 354823, 279397, 470112, 204785,
       186670, 120489, 391939, 118000, 269212, 432489, 440995,  86922,
      

# Inspecting Data Dictionary and Cleaning Data

In [1171]:
import pandas as pd
data_dictionary = pd.read_csv("supplyguard_data/data_dictionary.csv")
data_dictionary

,dataset,column,description
0,customers.csv,customer_id,Unique customer identifier
1,customers.csv,customer_name,Customer name
2,customers.csv,customer_type,"Individual, business or enterprise customer"
3,customers.csv,province,Customer province
4,customers.csv,city,Customer city
5,customers.csv,registration_date,Customer registration date
6,customers.csv,monthly_shipping_budget,Estimated monthly logistics budget
7,shipments.csv,shipment_id,Unique shipment identifier
8,shipments.csv,customer_id,Customer placing the shipment
9,shipments.csv,warehouse_id,Origin warehouse


In [1172]:
data_dictionary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   dataset      56 non-null     object
 1   column       56 non-null     object
 2   description  56 non-null     object
dtypes: object(3)
memory usage: 1.4+ KB


In [1173]:
data_dictionary.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
50    False
51    False
52    False
53    False
54    False
55    False
dtype: bool

In [1174]:
data_dictionary[data_dictionary.duplicated() == True]

,dataset,column,description


In [1175]:
data_dictionary.columns

Index(['dataset', 'column', 'description'], dtype='object')

In [1176]:
data_dictionary.dataset.unique()

array(['customers.csv', 'shipments.csv', 'deliveries.csv', 'drivers.csv',
       'vehicles.csv', 'warehouses.csv', 'delivery_labels.csv',
       'exchange_rates.csv'], dtype=object)

In [1177]:
data_dictionary.column.unique()

array(['customer_id', 'customer_name', 'customer_type', 'province',
       'city', 'registration_date', 'monthly_shipping_budget',
       'shipment_id', 'warehouse_id', 'shipment_date', 'shipment_type',
       'delivery_method', 'weight_kg', 'declared_value_zar',
       'distance_km', 'priority', 'delivery_id', 'driver_id',
       'vehicle_id', 'delivery_date', 'delivery_status',
       'delivery_duration_hours', 'delivery_distance_km', 'fuel_cost_zar',
       'customer_rating', 'attempt_number', 'delivery_hour',
       'driver_name', 'age', 'experience_years', 'license_type',
       'employment_type', 'home_province', 'performance_rating',
       'vehicle_type', 'vehicle_age_years', 'capacity_kg', 'fuel_type',
       'maintenance_score', 'current_mileage_km', 'warehouse_name',
       'warehouse_type', 'capacity_units', 'is_late', 'risk_reason',
       'date', 'currency', 'zar_rate'], dtype=object)

In [1178]:
data_dictionary.description.unique()

array(['Unique customer identifier', 'Customer name',
       'Individual, business or enterprise customer', 'Customer province',
       'Customer city', 'Customer registration date',
       'Estimated monthly logistics budget', 'Unique shipment identifier',
       'Customer placing the shipment', 'Origin warehouse',
       'Date shipment was created', 'Type of shipment', 'Delivery method',
       'Shipment weight', 'Declared shipment value',
       'Expected shipment distance', 'Shipment priority',
       'Unique delivery identifier', 'Shipment being delivered',
       'Assigned driver', 'Assigned vehicle', 'Delivery date',
       'Delivery status', 'Delivery duration', 'Actual delivery distance',
       'Estimated fuel cost', 'Customer delivery rating',
       'Number of delivery attempts', 'Hour delivery took place',
       'Unique driver identifier', 'Driver name', 'Driver age',
       'Driving experience', 'Driving licence category',
       'Employment arrangement', 'Driver home pr

# Inspecting Delivery labels and Cleanging Data

In [1179]:
import pandas as pd
delivery_labels = pd.read_csv("supplyguard_data/delivery_labels.csv")
delivery_labels

,delivery_id,is_late,risk_reason
0,DL000000001,1,Long delivery distance
1,DL000000002,0,Normal delivery
2,DL000000003,0,Normal delivery
3,DL000000004,0,Normal delivery
4,DL000000005,0,Normal delivery
...,...,...,...
999995,DL000999996,0,Normal delivery
999996,DL000999997,0,Normal delivery
999997,DL000999998,0,Normal delivery
999998,DL000999999,0,Normal delivery


In [1180]:
delivery_labels.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 3 columns):
 #   Column       Non-Null Count    Dtype 
---  ------       --------------    ----- 
 0   delivery_id  1000000 non-null  object
 1   is_late      1000000 non-null  int64 
 2   risk_reason  1000000 non-null  object
dtypes: int64(1), object(2)
memory usage: 22.9+ MB


In [1181]:
delivery_labels.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...  
999995    False
999996    False
999997    False
999998    False
999999    False
Length: 1000000, dtype: bool

In [1182]:
delivery_labels[delivery_labels.duplicated() == True]

,delivery_id,is_late,risk_reason


In [1183]:
delivery_labels.columns

Index(['delivery_id', 'is_late', 'risk_reason'], dtype='object')

In [1184]:
delivery_labels.is_late.unique()

array([1, 0])

In [1185]:
delivery_labels.risk_reason.unique()

array(['Long delivery distance', 'Normal delivery', 'Operational delay',
       'Low driver performance', 'Poor vehicle maintenance',
       'Early delivery', 'Late delivery hour'], dtype=object)